server:
  image: codeyu/ngrok
  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"
  volumes:
    - /data/ngrok:/myfiles
  environment:
    - DOMAIN="codeyu-ngrok.daoapp.io"
  command: /bin/sh /server.sh