server:
  image: codeyu/ngrok
  ports:
    - "8080:8080"
    - "8081:8081"
    - "4443:4443"
  volumes:
    - /data/ngrok:/myfiles
  environment:
    - DOMAIN="codeyu-ngrok.daoapp.io"
  command: /bin/sh /server.sh